### PR TITLE
Support Rails 7.2

### PR DESCRIPTION
**Pull request by AlexMooney**
Add Rails 7.2 to the CI and update some dependencies to versions which support Rails 7.2.

Closes https://github.com/braintree/pg_ha_migrations/issues/104

### CODE REVIEW

**Comment by AlexMooney** [comment]
@jcoleman I could use some help with the CI again. Not sure what the problem is.

**Comment by AlexMooney** [comment]
I'm going to be away from home for a couple of weeks. If anyone wants to take these changes and get them merged in the meantime, feel free! Don't let me be a blocker.

**Comment by elliotcm** [comment]
Hi @AlexMooney 

Do you know when you might be able to take another look at this?

**Comment by afuno** [comment]
@AlexMooney Hi. Please add support for Rails 8 (8.0.0 RC2).

**Comment by rkrage** [comment]
Hey folks, sorry for the delay. I'm looking into Rails 7.2 and 8 support this week

**Comment by rkrage** [comment]
Closing in favor of https://github.com/braintree/pg_ha_migrations/pull/108

**Pull request closed without merging**
